version: "3"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=$DB_DATA
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${DB_PORT}:5432'

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    user: root
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - '${MB_PORT}:3000'
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_TYPE=$DB_TYPE
      - MB_DB_DBNAME=$DB_NAME
      - MB_DB_PORT=$DB_PORT
      - MB_DB_USER=$DB_USER
      - MB_DB_PASS=$DB_PASS
      - MB_DB_HOST=$DB_HOST
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
  metabase-data:

    # Connect with psql: psql -h localhost -p 5432 -U admin -W postgres
